default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('PG_DATABASE_HOST') { 'localhost' } %>
  database: flaredown_development
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: flaredown_development

test:
  <<: *default
  database: flaredown_test

production:
  <<: *default
  host: <%= ENV.fetch('PG_DATABASE_HOST') { 'localhost' } %>
  pool: <%= ENV.fetch('DB_POOL') { 30 } %>
