version: '3'
volumes:
  postgres:
  mongodb:
  redis:
services:
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /data
    volumes:
      - postgres:/data
    ports:
      - 5432:5432
  mongodb:
    image: mongo:4.4.9
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis:3.2.6-alpine
    volumes:
      - redis:/data
    ports:
      - 6379:6379
