---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/checkins":
    get:
      summary: list checkins
      responses:
        '200':
          description: successful
    post:
      summary: create checkin
      responses:
        '200':
          description: successful
  "/api/checkins/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show checkin
      responses:
        '200':
          description: successful
    patch:
      summary: update checkin
      responses:
        '200':
          description: successful
    put:
      summary: update checkin
      responses:
        '200':
          description: successful
  "/api/conditions":
    get:
      summary: list conditions
      responses:
        '200':
          description: successful
    post:
      summary: create condition
      responses:
        '200':
          description: successful
  "/api/conditions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show condition
      responses:
        '200':
          description: successful
  "/api/countries":
    get:
      summary: list countries
      responses:
        '200':
          description: successful
  "/api/countries/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show country
      responses:
        '200':
          description: successful
  "/api/day_habits":
    get:
      summary: list day_habits
      responses:
        '200':
          description: successful
  "/api/day_habits/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show day_habit
      responses:
        '200':
          description: successful
  "/api/education_levels":
    get:
      summary: list education_levels
      responses:
        '200':
          description: successful
  "/api/education_levels/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show education_level
      responses:
        '200':
          description: successful
  "/api/ethnicities":
    get:
      summary: list ethnicities
      responses:
        '200':
          description: successful
  "/api/ethnicities/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show ethnicity
      responses:
        '200':
          description: successful
  "/api/passwords":
    post:
      summary: create password
      responses:
        '200':
          description: successful
  "/api/passwords/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show password
      responses:
        '200':
          description: successful
    patch:
      summary: update password
      responses:
        '200':
          description: successful
    put:
      summary: update password
      responses:
        '200':
          description: successful
  "/api/posts":
    get:
      summary: list posts
      responses:
        '200':
          description: successful
    post:
      summary: create post
      responses:
        '200':
          description: successful
  "/api/posts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show post
      responses:
        '200':
          description: successful
  "/api/profiles":
    get:
      summary: list profiles
      responses:
        '200':
          description: successful
  "/api/profiles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show profile
      responses:
        '200':
          description: successful
    patch:
      summary: update profile
      responses:
        '200':
          description: successful
    put:
      summary: update profile
      responses:
        '200':
          description: successful
  "/api/registrations/destroy":
    put:
      summary: delete registration
      responses:
        '200':
          description: successful
  "/api/registrations":
    post:
      summary: create registration
      responses:
        '200':
          description: successful
  "/api/searches":
    get:
      summary: show search
      responses:
        '200':
          description: successful
  "/api/sexes":
    get:
      summary: list sexes
      responses:
        '200':
          description: successful
  "/api/sexes/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show sex
      responses:
        '200':
          description: successful
  "/api/symptoms/{id}":
    get:
      summary: show symptom
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  symptom:
                    type: object
                    properties:
                      id:
                        type: integer
                        required: true
                      updated_at:
                        type: string
                        required: true
                      created_at:
                        type: string
                        required: true
                      type:
                        type: string
                        required: true
                      color_id:
                        type: integer
                        nullable: true
                      users_count:
                        type: integer
                        required: true
                      name:
                        type: string
                        required: true
                required:
                - symptom
  "/api/tags":
    get:
      summary: list tags
      responses:
        '200':
          description: successful
    post:
      summary: create tag
      responses:
        '200':
          description: successful
  "/api/tags/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show tag
      responses:
        '200':
          description: successful
  "/api/trackings":
    get:
      summary: list trackings
      responses:
        '200':
          description: successful
    post:
      summary: create tracking
      responses:
        '200':
          description: successful
  "/api/trackings/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show tracking
      responses:
        '200':
          description: successful
    delete:
      summary: delete tracking
      responses:
        '200':
          description: successful
  "/api/treatments":
    get:
      summary: list treatments
      responses:
        '200':
          description: successful
    post:
      summary: create treatment
      parameters: []
      responses:
        '200':
          description: successful
  "/api/treatments/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show treatment
      responses:
        '200':
          description: successful
  "/api/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      parameters: []
      responses:
        '200':
          description: successful
  "/api/weathers":
    get:
      summary: list weathers
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
  description: local documentation
