name: ERB lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - master

jobs:
  erb_lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: ERB lint
        run: |
          gem install erb_lint
          erblint --lint-all --autocorrect
