name: frontend

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - '.github/workflows/**'
            frontend:
              - 'frontend/**'
              - '.github/workflows/**'

  npm-test:
    strategy:
      matrix:
        node_version: ['12.22.6', '14.21']
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm install -g npm@7.0.0
      - run: npm install
        working-directory: ./frontend
      - run: npm run test
        working-directory: ./frontend

  node-next-test:
    strategy:
      matrix:
        node_version: ['16', '18', '20']
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm install -g npm@7.0.0
      - run: npm install
        working-directory: ./frontend
      - run: npm run test
        working-directory: ./frontend

  test-app:
    name: Test app
    needs: [ npm-test ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "done"
