name: frontend

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - master

env:
  NODE_VERSION: 12.22.6

jobs:
  test-app:
    name: Test app
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - run: npm install -g npm@latest
      - run: npm install
        working-directory: ./frontend
      - run: npm run test
        working-directory: ./frontend
