name: standardrb lint

on:
  push:
    branches:
      - '**'

jobs:
  ruby-lint:
    runs-on: ubuntu-latest
    container: 'ubuntu:18.04'
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2

      - name: Install System Dependencies
        run: |
          apt-get update && apt-get install -y build-essential libgmp3-dev libpq-dev zlib1g-dev git libssl1.0 ca-certificates postgresql-client libyaml-0-2
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6.8'
        env:
          ImageOS: ubuntu18

      - name: Configure Ruby
        run: |
          echo "gem: --no-ri --no-rdoc" > ~/.gemrc

      - name: Install Backend Dependencies
        run: |
          bundle install --without production -j5

      - name: Build & Run
        run: |
          bundle exec standardrb
