name: standardrb lint

on:
  push:
    branches:
      - '**'

jobs:
  ruby-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: backend
          bundler-cache: true

      - name: Build & Run
        run: |
          bundle exec standardrb
